
{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
  - {{ .Values.virtualService.host }}
  gateways:
  - {{ .Values.virtualService.gateway }}
  http:
  - route:
    - destination:
        host: {{ .Values.virtualService.service.name }}
        port:
          number: {{ .Values.virtualService.service.port }}
    {{- if .Values.virtualService.retries }}
    retries:
      attempts: {{ .Values.virtualService.retries.attempts }}
      perTryTimeout: {{ .Values.virtualService.retries.perTryTimeout }}
    {{- end }}
{{- end }}
