{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kibana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kibana
      annotations:
        sidecar.istio.io/inject: {{ .Values.kibana.istioInjection | default "true" }}
    spec:
      serviceAccountName: {{ .Values.kibana.serviceAccount }}
      containers:
        - name: kibana
          image: {{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}
          resources:
            limits:
              cpu: {{ .Values.kibana.resources.limits.cpu }}
              memory: {{ .Values.kibana.resources.limits.memory }}
            requests:
              cpu: {{ .Values.kibana.resources.requests.cpu }}
              memory: {{ .Values.kibana.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.kibana.service.targetPort }}
{{- end }}